### ISSUE TITLE
Panic  In Device::create_buffer     `MAP` usage can only be combined with the opposite `COPY`, requested BufferUsages(MAP_READ | COPY_DST | STORAGE)

### ISSUE THREAD

**Issue by mogambro** [ria8651/alex#1]
Hello!

Thanks again for letting us tinker with such cool projects!

Trying to run this I get:

```2023-10-10T22:02:30.719895Z  INFO alex::render_pipeline::load_anvil: skipping region assets/worlds/hermitcraft7/r.0.0.mca
2023-10-10T22:02:30.719986Z  INFO alex::render_pipeline::cpu_brickmap: recreating mipmaps for 1 bricks
2023-10-10T22:02:30.721223Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'main' panicked at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.2/src/backend/direct.rs:3019:5:
wgpu error: Validation Error

Caused by:
    In Device::create_buffer
    `MAP` usage can only be combined with the opposite `COPY`, requested BufferUsages(MAP_READ | COPY_DST | STORAGE)


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried different combinations of the BufferUsages in https://github.com/ria8651/alex/blob/master/src/render_pipeline/voxel_world.rs#L85 but to no avail.

Any ideas?

**Comment by mogambro** [comment]
Seems to be https://github.com/gfx-rs/wgpu/issues/3305

**Comment by ria8651** [comment]
i'm not currently using the counter buffer on the hybrid branch so that part should work for now

**Comment by mogambro** [comment]
Hm, I still get a grey screen running in release mode.

In debug I even get:

```
/bevy_render-0.12.0/src/texture/image.rs:514:9:
assertion `left == right` failed: Must not have incomplete pixel data.
  left: 4
 right: 0
stack backtrace:
   0:     0x55da40a8afbc - std::backtrace_rs::backtrace::libunwind::trace::h67a838aed1f4d6ec
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55da40a8afbc - std::backtrace_rs::backtrace::trace_unsynchronized::h1d1786bb1962baf8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55da40a8afbc - std::sys_common::backtrace::_print_fmt::h5a0b1f807a002d23
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55da40a8afbc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf84ab6ad0b91784c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55da40abc8ec - core::fmt::rt::Argument::fmt::h28f463bd1fdabed5
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   5:     0x55da40abc8ec - core::fmt::write::ha37c23b175e921b3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
   6:     0x55da40a85f1e - std::io::Write::write_fmt::haa1b000741bcbbe1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
   7:     0x55da40a8ada4 - std::sys_common::backtrace::_print::h1ff1030b04dfb157
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55da40a8ada4 - std::sys_common::backtrace::print::hb982056c6f29541c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55da40a8c6d3 - std::panicking::default_hook::{{closure}}::h11f92f82c62fbd68
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
  10:     0x55da40a8c3f4 - std::panicking::default_hook::hb8810fe276772c66
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
  11:     0x55da40a8ccc5 - std::panicking::rust_panic_with_hook::hd2f0efd2fec86cb0
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
  12:     0x55da40a8cbc1 - std::panicking::begin_panic_handler::{{closure}}::h3651b7fc4f61d784
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
  13:     0x55da40a8b4e6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbc468e4b98c7ae04
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55da40a8c912 - rust_begin_unwind
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
  15:     0x55da40ab9b65 - core::panicking::panic_fmt::h979245e2fdb2fabd
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
  16:     0x55da40aba0a1 - core::panicking::assert_failed_inner::h717c029df0cb454b
  17:     0x55da3fc78a3e - core::panicking::assert_failed::hff8a114804821404
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:270:5
  18:     0x55da3f09305f - bevy_render::texture::image::Image::new_fill::h917816e579d58ddf
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.0/src/texture/image.rs:514:9
  19:     0x55da3dfc733f - <alex::render_pipeline::main_pass::FallbackBeamTexture as bevy_ecs::world::FromWorld>::from_world::h07a5799e9b065f15
                               at /home/nerdachse/projects/game_dev/bevy_stuff/alex/src/render_pipeline/main_pass/mod.rs:251:36
  20:     0x55da3e02b411 - bevy_ecs::world::World::init_resource::h7af986e1eee80e84
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.0/src/world/mod.rs:1053:25
  21:     0x55da3dfa2243 - bevy_app::app::App::init_resource::h6a339987df4f3004
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:577:9
  22:     0x55da3dfc3361 - <alex::render_pipeline::main_pass::MainPassPlugin as bevy_app::plugin::Plugin>::build::h9a411b9c9ebe5bd0
                               at /home/nerdachse/projects/game_dev/bevy_stuff/alex/src/render_pipeline/main_pass/mod.rs:24:9
  23:     0x55da40738916 - bevy_app::app::App::add_boxed_plugin::{{closure}}::h35df0194e564bfb7
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:638:55
  24:     0x55da4073f7b9 - core::ops::function::FnOnce::call_once::hc34170af32bd9de3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  25:     0x55da40743819 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf4c63bc5d2d92928
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  26:     0x55da4073f053 - std::panicking::try::do_call::h61c4ae6c369c3384
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  27:     0x55da40741e0b - __rust_try
  28:     0x55da4073efde - std::panicking::try::h429196fc33e59d0a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  29:     0x55da4074713a - std::panic::catch_unwind::h5561edbe293c0f2f
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  30:     0x55da4073861b - bevy_app::app::App::add_boxed_plugin::hb93cb2a3a38edf66
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:638:22
  31:     0x55da3dfdbfd0 - <P as bevy_app::plugin::sealed::Plugins<bevy_app::plugin::sealed::PluginMarker>>::add_to_app::hc47eff480035b7b0
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/plugin.rs:95:17
  32:     0x55da3dfa01c8 - bevy_app::app::App::add_plugins::h9818c9366792d89c
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:737:9
  33:     0x55da3e007b2e - <alex::render_pipeline::RenderPlugin as bevy_app::plugin::Plugin>::build::h20be5fb44407a837
                               at /home/nerdachse/projects/game_dev/bevy_stuff/alex/src/render_pipeline/mod.rs:26:9
  34:     0x55da40738916 - bevy_app::app::App::add_boxed_plugin::{{closure}}::h35df0194e564bfb7
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:638:55
  35:     0x55da4073f7b9 - core::ops::function::FnOnce::call_once::hc34170af32bd9de3
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  36:     0x55da40743819 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf4c63bc5d2d92928
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  37:     0x55da4073f053 - std::panicking::try::do_call::h61c4ae6c369c3384
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  38:     0x55da40741e0b - __rust_try
  39:     0x55da4073efde - std::panicking::try::h429196fc33e59d0a
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  40:     0x55da4074713a - std::panic::catch_unwind::h5561edbe293c0f2f
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  41:     0x55da4073861b - bevy_app::app::App::add_boxed_plugin::hb93cb2a3a38edf66
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:638:22
  42:     0x55da3e00ae40 - <P as bevy_app::plugin::sealed::Plugins<bevy_app::plugin::sealed::PluginMarker>>::add_to_app::h1772c2a331ca4d0e
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/plugin.rs:95:17
  43:     0x55da3dffd6aa - <(S0,S1,S2,S3) as bevy_app::plugin::sealed::Plugins<(bevy_app::plugin::sealed::PluginsTupleMarker,P0,P1,P2,P3)>>::add_to_app::h9fbba9616f654db8
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/plugin.rs:121:23
  44:     0x55da3df9fc5f - bevy_app::app::App::add_plugins::h2ec7f4694a84d55a
                               at /home/nerdachse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.0/src/app.rs:737:9
  45:     0x55da3e00465b - alex::main::he1b36377cc7ce739
                               at /home/nerdachse/projects/game_dev/bevy_stuff/alex/src/main.rs:15:5
  46:     0x55da3dfb1c6b - core::ops::function::FnOnce::call_once::h19e96018c6973c9d
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  47:     0x55da3df60b7e - std::sys_common::backtrace::__rust_begin_short_backtrace::h654e1481863cf631
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:154:18
  48:     0x55da3df62561 - std::rt::lang_start::{{closure}}::hf6abe58dd23c79e8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:166:18
  49:     0x55da40a7ec9b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf9057cfaeeb252e2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
  50:     0x55da40a7ec9b - std::panicking::try::do_call::h629e203a624883e4
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  51:     0x55da40a7ec9b - std::panicking::try::h7b61614724d6a4f1
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  52:     0x55da40a7ec9b - std::panic::catch_unwind::h354ac1c0268491d8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  53:     0x55da40a7ec9b - std::rt::lang_start_internal::{{closure}}::h919fee3c5ba8f617
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
  54:     0x55da40a7ec9b - std::panicking::try::do_call::h54583f67455bff32
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  55:     0x55da40a7ec9b - std::panicking::try::hb0e12c4e01d39dc2
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  56:     0x55da40a7ec9b - std::panic::catch_unwind::h367b6339e3ca9a3b
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  57:     0x55da40a7ec9b - std::rt::lang_start_internal::ha5ce8533eaa0fda8
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
  58:     0x55da3df6253a - std::rt::lang_start::he5cf687a07816b5c
                               at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:165:17
  59:     0x55da3e00586e - main
  60:     0x7fb2e6655cd0 - <unknown>
  61:     0x7fb2e6655d8a - __libc_start_main
  62:     0x55da3df5e965 - _start
  63:                0x0 - <unknown>
```

Not sure what to make out of that.

**Comment by ria8651** [comment]
this should be fixed by https://github.com/ria8651/alex/commit/f5e260a6acb29cd0dd93512c8848ac3f304c5126, i didn't notice it because i always run in release mode and for some reason it worked.

**Comment by mogambro** [comment]
Yup, it works, thanks a bunch!
